### ISSUE TITLE
Loop basic blocks splitting

### ISSUE THREAD

**Issue by denismerigoux** [cretonne/cretonne#106]
Right now, the loop analysis describes the loop by a header `Ebb` and a list of `Ebb`s pertaining to the loop. However, because `Ebb` are _extended_ basic blocks, this description include instructions that are not part of the loop (they are after the back edge branch instruction in the `Ebb`),

This is a problem because the LICM pass will move upstream instructions that are not in the loop. It does't break the code because moving SSA definitions upwards (in the dominator tree) is always allowed but it will break code locality.

The way to solve this problem is to represent loops in the loop analysis as a list of couples `(Ebb,Inst)` where `Inst` is the last back edge to appear in `Ebb`, `Ebb` being part of the loop. Then the LICM pass would stop moving instructions around when it reaches `Inst`.

I will implement that later, the issue is just a reminder.

**Comment by stoklund** [comment]
One problem with this representation is that parts of an EBB can belong to three or more loops if it contains back-edges to different loop headers.

It would be possible to enforce a constraint that an EBB belongs to at most two loops. The loop analysis can split any EBBs that would belong to more than two loops.

**Comment by denismerigoux** [comment]
Implemented in #133

**Comment by sunfishcode** [comment]
This is implemented in #133, which is merged in the better_licm pass. Further development tracked by #393.
