### ISSUE TITLE
Regalloc verifier error

### ISSUE THREAD

**Issue by sunfishcode** [Cretonne/cretonne#180]
```
test regalloc
set is_64bit=1
isa intel haswell

function %test(b1) -> i32 native {
    sig0 = () native
    fn0 = sig0 %fn1

ebb3(v0: b1):
    brz v0, ebb2(v0)
    trap user0

ebb2(v2: b1):
    call fn0()
    jump ebb1

ebb1:
    v1 -> v2
    brnz.b1 v1, ebb1
    v1 -> v2
    jump ebb2(v1)
}
```

FAIL x.cton: regalloc(%test1): inst0: v1 and v4 must be in the same virtual register

The same failure occurs with `test compile`.

**Comment by stoklund** [comment]
Saving this one for @bnjbvr

**Comment by sunfishcode** [comment]
This testcase now gets an error, "duplicate entity: v1", and it passes when that issue is corrected, so this bug no longer reproduces.
