### ISSUE TITLE
"Expected register: Unassigned" error in `docs/example.cton`

### ISSUE THREAD

**Issue by joshuawarner32** [cretonne/cretonne#181]
I just started poking around with cretonne, and I noticed that the following command failed:

```
$ cargo run -- compile -vp --isa intel docs/example.cton
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/cton-util compile -vp --isa intel docs/example.cton`
thread 'main' panicked at 'Expected register: Unassigned', lib/cretonne/src/ir/valueloc.rs:40:17
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: cretonne::ir::valueloc::ValueLoc::unwrap_reg
   7: cretonne::regalloc::diversion::RegDiversions::reg
   8: cretonne::regalloc::coloring::Context::program_input_constraints
   9: cretonne::regalloc::coloring::Context::visit_inst
  10: cretonne::regalloc::coloring::Context::visit_ebb
  11: cretonne::regalloc::coloring::Context::run
  12: cretonne::regalloc::coloring::Coloring::run
  13: cretonne::regalloc::context::Context::run
  14: cretonne::context::Context::regalloc
  15: cretonne::context::Context::compile
  16: cton_util::compile::handle_module
  17: cton_util::compile::run
  18: cton_util::cton_util
  19: cton_util::main
  20: __rust_maybe_catch_panic
  21: std::rt::lang_start
  22: main
```

The failure seems to happen with both intel an riscv, but arm32 and arm64 both show a different "not yet implemented" error.  I tried poking around in the history a bit to see if I could bisect the failure, but as far as I can tell, the `compile` command was introduced fairly recently, and `example.cton` exhibits the same failure ever since `compile` was introduced.

I'm happy to dig further in debugging, if someone could point me in the right direction.

**Comment by sunfishcode** [comment]
The most immediate problem here is that `cton-util compile` wasn't enabling the verifier by default. I've now fixed this, so if you update and rerun `cton-util compile`, it'll show you the real problem:
```
inst1: Store must have an encoding
inst1: stack_store.f64 v2, ss0
```
[...]
```
[-]                                 stack_store v2, ss0
```

Most instructions in that testcase get encoded, especially with the 64-bit intel target (`--set is_64bit=1 --isa intel`), but the ones with `[-]` are instructions that don't, because they aren't implemented in the legalizer yet. That might be an interesting place to start.

(When the verifier is disabled, this problem goes unnoticed, and it creates trouble later on in the middle of register allocation, which is what the `Expected register: Unassigned` message is a symptom of.)

As you noticed, the `compile` command is new, and there are still some rough edges. Feel free to ask questions!

**Comment by stoklund** [comment]
We should probably just have the verifier enabled by default.

**Comment by joshuawarner32** [comment]
It looks to me like the stack_store instruction in general is missing some handling when compiling. It's not just the f64 variant, as was my first guess.  A few options come to mind:
* Make sure it disappears in an equivalent of the LLVM "mem2reg" pass, fairly early in the compilation process
* Legalize it into a normal store, which (presumably?) already has the correct encoding support
* Actually add an encoding for stack_store

In order for the first option to be a general solution, the pointer to the stack location would have to not be allowed to escape (and more specifically, not allowed to be used at all outside of the context of a stack_{load,store} instruction in the same function).  At a glance, it *looks* like that assumption might hold, but it's not totally clear to me.

For the second option, is there a target-independent legalization phase that we can tap into here?  Or would that need to be done separately for each of the targets?

The third option (adding an encoding) seems weird to me because it preserves high-level information far longer than necessary in the pipeline - but with what little I know about cretonne, I have a hard time ruling it out as the right option.

What's the right path here?  Am I missing something obvious?

**Comment by sunfishcode** [comment]
`stack_store` etc. could indeed be optimized in a mem2reg-style pass. We're currently using [on-the-fly SSA construction](https://github.com/stoklund/cretonne/blob/master/lib/frontend/src/ssa.rs), so mem2reg has not been as urgent. However, on-the-fly SSA construction requires front-ends to know which local variables have their address taken up front, where a mem2reg-style pass wouldn't, so mem2reg is still something that could be considered.

A mem2reg pass would indeed have to examine every use of a stack slot to make sure they're all plain `stack_load`/`stack_store`. For comparison, LLVM's mem2reg does this too. It's basically sufficient.

All that said, actual address-taken variables can't be optimized away by either approach, so we'll ultimately need legalization for `stack_store` and `stack_load` in any case. As you mention in your second list item, the first step is to add support for legalizing them into `stack_addr` and normal `store`/`load`; see the note [here](https://cretonne.readthedocs.io/en/latest/langref.html#inst-stack_addr). This step should be doable as a target-independent legalization.
