### ISSUE TITLE
Make cton-util compile disassemble machine code

### ISSUE THREAD

**Issue by sunfishcode** [cretonne/cretonne#259]
`cton-util compile` is evolving into a command to invoke the code generator and display the output. Currently it displays the final Cretonne IR, and [the output byte sequence](https://github.com/Cretonne/cretonne/blob/master/src/compile.rs#L102).

For example, when running `cton-util compile --print --set is_64bit=1 --isa intel filetests/isa/intel/abi32.cton`, the last line looks like:
> .byte 64, 85, 72, 137, 229, 64, 83, 65, 84, 65, 85, 65, 86, 65, 87, 72, 131, 196, 248, 72, 131, 196, 8, 65, 95, 65, 94, 65, 93, 65, 92, 64, 91, 64, 93, 195

which is great if you're an assembler, but not very readable for humans :-).

There are a few different disassembler crates on crates.io, though I don't know the pros and cons. We should pick one, and use it in `cton-util compile` to print disassembled instructions rather than just raw bytes.

**Comment by pchickey** [comment]
Related, it would be helpful to have a test suite that exhaustively tests all of the instruction encodings and makes sure their disassembly looks ok. This would have caught some of the problems we had with mov r13 encodings.

**Comment by sunfishcode** [comment]
Yeah, I think a separate issue for that would be good.

**Comment by sunfishcode** [comment]
Yep!
