### ISSUE TITLE
Say "IR" instead of "IL"?

### ISSUE THREAD

**Issue by sunfishcode** [Cretonne/cretonne#267]
"IL" stands for "intermediate language". "IR" which stands for "intermediate representation".

I think I was taught once that "intermediate language" referred to the abstract language that is shared when you have a text representation and a binary representation of the same conceptual content. However, the internet doesn't seem to agree with that interpretation:

https://www.quora.com/What-is-the-dIfference-between-intermediate-representation-and-intermediate-language
https://en.wikipedia.org/wiki/Intermediate_representation#Intermediate_language

With those interpretations, it's kind of debatable whether Cretonne's IR is an IL, but calling it an IR wouldn't be incorrect and wouldn't miss out on much. So it's worth considering stopping saying "IL" and just say "IR" everywhere, to be more consistent and avoid potential confusion.

**Comment by tyler** [comment]
+1. I have had to explain “IL” too many times. :)
