### ISSUE TITLE
Use the wabt crate

### ISSUE THREAD

**Issue by sunfishcode** [cretonne/cretonne#270]
Currently running the in-tree wasm tests requires the `wat2wasm` command be installed. There's now a [wabt crate](https://crates.io/crates/wabt), so we should switch to using that, with an explicit dependency, instead.

**Comment by pepyakin** [comment]
I thin this should by closed by https://github.com/cretonne/cretonne/pull/347

**Comment by sunfishcode** [comment]
Yep!
