### ISSUE TITLE
Update to rustfmt-preview

### ISSUE THREAD

**Issue by pchickey** [cretonne/cretonne#277]
"Old" rustfmt 0.9.0 is getting long in the tooth, and is at odds with some of clippy's linting rules. Additionally, as implemented in #276, Clippy must be used via a nightly cargo.

So, the real issue is, do require a nightly toolchain be present on the system so that an up-to-date rustfmt (and clippy) can be used?

**Comment by sunfishcode** [comment]
Yeah; rustfmt 0.9.0 also has some [odd bugs](https://github.com/Cretonne/cretonne/blob/master/lib/frontend/src/frontend.rs#L155). It'd be great to upgrade to something newer.

On the other hand, rustfmt is something we run in the CI script, so we effectively expect all contributors to run it, and I'm hesitant to require all contributors have nightly installed. For example, people who install Rust from Ubuntu packages, even the latest in-development versions, [only have stable rustc](https://packages.ubuntu.com/bionic/devel/rustc). On the third hand though, I don't actually know how many people use those packages, versus just using rustup.

So I'm not sure which way is best.

**Comment by pchickey** [comment]
Speaking to some colleagues who are better plugged in to the rust community, it sounds like using rustup to install rustfmt is now very common. Additionally, there isn't a clear "end date" when the new rustfmt will work without rustup - it sounds like its prescribed installation method is now `rustup component add rustfmt-preview`.

So, for better or worse, we may either be stuck on "old rustfmt" forever, or need to have rustup around.

**Comment by sunfishcode** [comment]
Oh, cool -- last time I looked at the docs, rustfmt-preview required nightly, but that's [no longer the case](https://github.com/rust-lang-nursery/rustfmt/commit/017fdc56f117ae1c4607d564680f948c9366301c#diff-04c6e90faac2675aa89e2176d2eec7d8), which is a nice development.

And it looks like they now have instructions for setting up [rustfmt for CI](https://github.com/rust-lang-nursery/rustfmt#checking-style-on-a-ci-server), which is also a good sign.

It looks like it still does require rustup. But if many other projects using Rust are going this way, staying with 0.9.0 will make it inconvenient for people who work on multiple projects. So I'd like to learn a little more still, but I'm starting to think maybe we should update.

**Comment by sunfishcode** [comment]
I created a [rustfmt-preview-1.25](https://github.com/Cretonne/cretonne/tree/rustfmt-preview-1.25) branch with rustfmt-preview formatting. Unfortunately, the Travis build [failed](https://travis-ci.org/Cretonne/cretonne/jobs/360430676). It looks like the Travis build is somehow still using the old version of rustfmt, and I don't yet know why.

One gotcha I've encountered so far is that nightly rustfmt-preview does more things than stable rustfmt-preview does, so if you switch between toolchain versions when doing development, you may occasionally see irrelevant formatting diffs. I've attempted to reduce the effects of this by formatting everything with nightly rustfmt-preview and then reformatting back to the old version.

**Comment by sunfishcode** [comment]
I believe I've now figured out what the problem was, and created #348.

**Comment by pepyakin** [comment]
I've uninstalled rustfmt and now `./test-all.sh` says:

```
rustfmt not available; formatting not checked!

If you are using rustup, rustfmt can be installed via
"rustup component add --toolchain=stable rustfmt-preview", or see
https://github.com/rust-lang-nursery/rustfmt for more information.
```

but since I already have added component `rustfmt-preview` this command outputs:

```
info: component 'rustfmt-preview' for target 'x86_64-apple-darwin' is up to date
```

removing and adding it again doesn't solve the issue

**Comment by sunfishcode** [comment]
If you do `rustup update` after the `rustup component add ...`, does rustfmt work for you?
