### ISSUE TITLE
Design a Module interface

### ISSUE THREAD

**Issue by sunfishcode** [cretonne/cretonne#288]
https://github.com/Cretonne/cretonne/pull/190 was an early attempt at defining a simple `Module` concept, but it was a very simplistic approach, with everything stored in memory at once, rather than supporting streaming compilation. We should design a new API to allow compilation of a group of functions together, as well as static data.

It might be a good idea to make `Module` a trait, rather than a struct. Then, we could have have trait implementations  such as one that uses [Faerie](https://github.com/m4b/faerie), and one that works as a JIT, allocating functions in executable pages in memory and making the callable. I think one of the key concepts of such a `Module` is that functions and data within a `Module` can reference each other with fixed (after relocation) offsets. They can reference things outside the module too, but in some cases this might require use of GOT, PLT, or other indirection mechanisms, to allow those things to be repositioned after relocation. Of course, in all cases the specific relocations would be controlled by settings, such as PIC vs not, and so on.

The trait could have an interface resembling Faerie's [`Artifact`](https://docs.rs/faerie/0.1.0/faerie/artifact/struct.Artifact.html), allowing functions and data to be declared and defined. And, it would need a way to interface with [`Context`](https://docs.rs/cretonne/0.4.1/cretonne/struct.Context.html) and [`FunctionBuilder`](https://docs.rs/cretonne-frontend/0.4.1/cton_frontend/struct.FunctionBuilder.html) to make it easy to build functions, compile them, and relocate them.

I'm expecting to build up a design, post increasingly detailed comments here, and eventually write a PR. Feedback is welcome, including ideas for going in a completely different direction. Or if anyone else is interested in coding up any part of this, I'd be happy to mentor things.

**Comment by sunfishcode** [comment]
Here's an initial sketch of what I'm picturing.
```rust
/// Linkage refers to where an entity is defined and who can see it.
enum Linkage {
    /// Defined outside of a module.
    Import,
    /// Defined inside the module, but not visible outside it.
    Local,
    /// Defined inside the module, and visible outside it.
    Export,
}

/// A `Module` is a trait for collecting functions and data objects, and linking them together.
trait Module {
    fn declare_function(&mut self, name: ir::ExternalName, linkage: Linkage) -> FuncId;
    fn declare_data(&mut self, name: ir::ExternalName, linkage: Linkage, writeable: bool) -> DataId;

    /// Define a function, producing the function body from the given `Context`.
    /// Relocations for the function are added automatically, so there's no need
    /// to call `func_funcaddr` or `func_dataaddr`.
    fn define_function(&mut self, func: FuncId, ctx: &cretonne::Context);

    /// Define a zero-initialized data object of the given size.
    fn define_data_with_zeros(&mut self, data: DataId, size: usize);

    /// Define a data object sized and initialized from `contents`.
    fn define_data_with_bytes(&mut self, data: DataId, contents: &[u8]);

    /// Write the address of `what` plus `addend` into the data for `data` at
    /// `offset`. `data` must refer to a defined data object.
    fn write_data_funcaddr(&mut self, data: DataId, offset: usize, what: FuncId, usize: addend);
    fn write_data_dataaddr(&mut self, data: DataId, offset: usize, what: DataId, usize: addend);

    /// Perform all outstanding relocations on the given entity. This requires
    /// all `DefinedHere` and `Export` entities referenced to be defined.
    fn finalize_function(&mut self, func: FuncId);
    fn finalize_data(&mut self, data: DataId);

    /// Finalize all functions and data objects.
    fn finalize_all(&mut self);
}

/// A `FaerieModule` implements `Module` and emits ".o" files using the
/// `faerie` library.
struct FaerieModule {
    artifact: faerie::Artifact,
}

impl FaerieModule {
    pub fn new(...) {
       ...
    }

    /// Call `emit` on the faerie `Artifact`, producing bytes in memory.
    pub fn emit<O: faerie::Object>(&self) -> Result<Vec<u8>, Error> {
       ...
    }

    /// Call `write` on the faerie `Artifact`, writing to a file.
    pub fn write<O: faerie::Object>(&self, mut sink: File) -> Result<(), Error> {
       ...
    }
}

impl Module for FaerieModule {
    ...
}

/// A `JITModule` implements `Module` and emits code and data into
/// memory where it can be directly called and accessed.
struct JITModule {
     ...
}

impl JITModule {
    pub fn new(...) {
       ...
    }

    /// Return a pointer to the function referred to by `func`, which can
    /// be transmuted into a Rust function type and called.
    pub fn get_raw_funcaddr(&self, func: FuncId) -> *const u8;

    /// Return a function pointer for `func`.
    pub fn get_funcaddr<FuncTy>(&self, func: FuncId) -> FuncTy;

    /// Return a data pointer for `data`, which can be transmuted into a
    /// Rust data type and stored or loaded through.
    pub fn get_raw_dataaddr(&self, data: DataId) -> *const u8;
    pub fn get_raw_dataaddr_mut(&self, data: DataId) -> *mut u8;

    /// Return a data pointer for `data`, which can be transmuted into a
    /// Rust data type and stored or loaded through. `data` must refer to
    /// a non-`Import` data object.
    pub fn get_dataaddr(&self, data: DataId) -> &[u8];
    pub fn get_dataaddr_mut(&self, data: DataId) -> &mut [u8];
}

impl Module for JITModule {
    ...
}
```

**Comment by lachlansneff** [comment]
That's looks good to me. I've been working on designing the process of compiling modules in nebulet and having something standardized would be useful.

**Comment by sunfishcode** [comment]
#294 takes the above a step further. I split `Module` into two pieces, a `Backend` trait and a `Module` frontend struct, making it easier to share code between trait implementations, and simplifying the trait interface. I expect the design will continue to evolve as the implementation progresses.

**Comment by sunfishcode** [comment]
I now have a basic JIT demo up and running using the new SimpleJIT API: https://github.com/sunfishcode/simplejit-demo

**Comment by sunfishcode** [comment]
The [SimpleJIT Demo](https://github.com/sunfishcode/simplejit-demo) now has an example that has a loop, a static data object, and a call to a libc function. And it can say "hello world"!

**Comment by sunfishcode** [comment]
#294 has now landed, and development is proceeding on master.
