### ISSUE TITLE
Heap address legalization should consider guard pages

### ISSUE THREAD

**Issue by tyler** [Cretonne/cretonne#295]
Hello!

In the heap address legalization code (https://github.com/Cretonne/cretonne/blob/master/lib/cretonne/src/legalizer/heap.rs#L33-L40), neither the dynamic nor the static heap address functions take into account the size or existence of the guard pages following the heap. I think that taking that into consideration should let us elide many of the bounds checks that Cretonne currently generates. 

@sunfishcode I just wanted to run this by you to make sure I'm not missing something before I put in a PR to fix it.

Thanks!

**Comment by sunfishcode** [comment]
The `static_addr` case knows the case where you have >=4GiB mapped and don't need any bounds checks at all -- that's the `limit < 0xffff_ffff` check.

It doesn't do anything clever for the case where the mapped region is smaller than that. To do that, you'd need to do actual bounds-check elimination. The simple form is: given a load/store to some address `x`, loads/stores to `x` dominated by it don't need a bounds check. Then, you can extend that logic to take advantage of guard pages: subsequent loads/stores to `x + i` where i is within the guard region don't need a bounds check.

**Comment by tyler** [comment]
That makes sense. But as far as I understand, the mapped region is actually supposed to be the bound on the HeapStyle + the guard size on the HeapData, no? I guess I'm struggling to understand why you would need to bounds check something that is definitively within that range. Apologies if this is a dumb question.

**Comment by sunfishcode** [comment]
Are you looking at a case where heap bound + guard size >= 4 GiB? If so, that's not how static heaps are expected to be used. If you're planning to grab that much address space, you're expected to set your heap bound to 4 GiB (even if that's larger than the wam max_size field), and use guard pages to provide extra space beyond that for handling constant offsets.

**Comment by tyler** [comment]
> Are you looking at a case where heap bound + guard size >= 4 GiB?

Yeah, that's the exact case. I just realized the way we were thinking about the relationship between guard pages and heap bounds was off. I was considering the heap bound to the be the maximum amount that I might actually allocate, versus the amount that I have reserved.

I'll close this out. Thank you for the explanation, @sunfishcode!
