### ISSUE TITLE
MyPy 0.600 flags new issues in cretonne_codegen/meta

### ISSUE THREAD

**Issue by pchickey** [cretonne/cretonne#323]
The latest MyPy release, 0.600, has "strict optional checking" enabled by default, which encounters a giant pile of issues that were not flagged before.

With --no-strict-optional passed as a command line flag, it still fails to infer the type of some values.

Some work is required to diagnose and fix the issues that 0.600 flags. Until then, the CI script will use version 0.521 (set in #321).

**Comment by sunfishcode** [comment]
This issue is starting to show up in places other than CI, so I'm starting to work on it. I have an experimental branch [here](https://github.com/cretonne/cretonne/tree/mypy-0.600).
