### ISSUE TITLE
Question: feasibility of a Dalvik/dex backend?

### ISSUE THREAD

**Issue by akavel** [cretonne/cretonne#327]
Would it be hard to add a Dalvik/dex backend? I'm interested in maybe trying. Hiw would you evaluate feasibility of such an idea? AFAIU, Dalvik is a register-based VM, so maybe doable?

I know x86 assembly and C++; I don't know Dalvik, but at a first glance the instruction set looks reasonably small; I don't know Rust but I totally want to learn.

If I wanted to start hacking, should I jump into https://github.com/cretonne/cretonne/tree/master/lib/codegen/src/isa/ and start exploring the contents of arch subdirs, then try to add a new one based on those?

**Comment by sunfishcode** [comment]
I think such a thing would be possible, though how well it works will depend on what you're planning to do with it. Do the programs you're expecting to run need raw pointers? Do they need access to Dalvik's GC? Are you interested in translating WebAssembly, or some other source language?

Also, might I ask what sparks your interest in Dalvik? If you can tell me more about what you're interested in doing, I may be able to make more useful suggestions.

**Comment by akavel** [comment]
Starting from the end: my high level interest is to be able to write mobile apps without having to download the Android SDK environment, which I find super bloated and unwieldy, and repeatedly hit a wall trying to force it to my will. I'm trying to explore various paths which could get me to this goal. One of those ideas was to maybe try [using some sane language, and compiling it to Dalvik assembly](https://softwarerecs.stackexchange.com/q/50000/4980). I thought, maybe this could be Rust, compiled to WebAsm, then translated to Dalvik? In the end, I seem to have actually found a solution during this research binge. Somewhat unexpectedly to me, [Elm](http://elm-lang.org/) in context of a [Progressive Web App](https://developers.google.com/web/progressive-web-apps/) (via [create-elm-app](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#making-a-progressive-web-app) helper) seems to be promising.

Based on this background, my interest is/was in translating WebAsm emitted from some other source language. As to the other questions, I'm not sure; I don't know either WebAsm nor Dalvik well enough; that's one of the reasons I've actually decided to ask this question, in hope that someone here would be more knowledgeable and could sanity-check if that idea is in any way feasible! At least to the extent of being worth trying/researching.

**Comment by jrmuizel** [comment]
Was running Rust natively on Android instead of compiled to Dalvik not an option?

**Comment by akavel** [comment]
The thing is to be able to access the various Android APIs, first and foremost GUI building.

**Comment by Nemikolh** [comment]
That is possible through JNI. While it would require a fair amount of work, in my opinion, it would still be less than converting WebAssembly to dalvik and then bringing GUI APIs to Rust.

**Comment by pepyakin** [comment]
afaik, not all APIs are accessible thru JNI.

There is another option. Instead of translating directly to dex you can translate your program to java’s .class and then using `dx` convert it into dex. The good thing that this already might be possible with github.com/cretz/asmble

**Comment by Nemikolh** [comment]
Oh interesting! Do you have a reference that show that? I couldn't find APIs labelled as restricted in the documentation from use through JNI. The only thing [I found](https://developer.android.com/preview/restrictions-non-sdk-interfaces) is for non-sdk interfaces. From a practical experience I never encountered any issues with JNI from Rust (but I only used the Bluetooth APIs).

**Comment by pepyakin** [comment]
oh sorry, you’re totally right, since android framework is java-ish API there should be no problems in calling these API from JNI. I confused it with native NDK apis - although they provide direct access to android system they are by no means complete

**Comment by akavel** [comment]
Is it possible to compile the JNI part without downloading the whole Android SDK? As I said, I want to avoid it (otherwise I'd just code in Java/Kotlin).

Hm; maybe just synthetically generating Dalvik bytecode corresponding to the JNI part would be a viable approach? This feels like a more limited and thus simpler to implement task.

**Comment by Nemikolh** [comment]
@akavel With JNI, classes and method are loaded at runtime, so every class/method lookup happens on your Android device. There's no need for the Android SDK for that. However to run your Rust code on the device, you will need the Android NDK and at least the [platform tools](https://developer.android.com/studio/releases/platform-tools). The former is needed to compile your code (and to link against some C code IIRC) while the latter is needed to install your apk on a device.

You should have a look at this project [android-rs-glue](https://github.com/tomaka/android-rs-glue). The `cargo-apk` show how's the build process is roughly setup (note: last time I checked the build step where specific to a NDK version, more recent version of the NDK broke `cargo-apk`).

> maybe just synthetically generating Dalvik bytecode corresponding to the JNI part would be a viable approach?

It might, but you would still need to expose those APIs to Rust in order to use them. 
Which means generating Rust code, so you might as well generate JNI code for those APIs. (Maybe somebody has already started such a project?)

**Comment by akavel** [comment]
Hm; I don't understand well enough how JNI works, so I think I won't be able to discuss this any more at this time. My inuition tells me, that theoretically no tools from Android SDK/NDK should be needed, and given that the final result is a .dex, it should be theoretically possible to write a "helper app" generating some minimal scaffolding required to wrap a Rust nugget in a .dex file, in a way that it has access to the runtime "JNI" API of an Android host. But I understand that this is not in any way related to cretonne anymore, so here's probably not the place to discuss this. Thanks for all the hints!

**Comment by sunfishcode** [comment]
Closing, as it sounds like your questions are answered!
