### ISSUE TITLE
Make Capstone an optional dependency

### ISSUE THREAD

**Issue by 6A** [cretonne/cretonne#382]
I think it would be easy to make `capstone` an optional dependency introduced using a Cargo feature, since it is only [used in a single file](https://github.com/cretonne/cretonne/blob/88fc2303e77e6109cbef58d90acd7ccac3feb5f4/src/compile.rs), for a single purpose throughout cretonne. Furthermore, right now showing the disassembly of what we built is more of a "cool feature" than something we actively advertise or support, and thus I think it makes sense to make it optional, thus dropping a dependency on an external library.

**Edit**: This one is easy. Say the word and I'll do it myself.

**Comment by sunfishcode** [comment]
Cretonne is organized as a collection of crates -- every directory under `lib` is a crate, and the top level Cargo.toml is its own crate. The library crates have few dependencies, and these are what our users typically use. The top-level crate is mainly used by people working on Cretonne itself, so it can more easily take on dependencies like capstone if they proved useful developer-facing features.

**Comment by 6A** [comment]
That's a good point. In any case I implemented my suggestion and submitted a PR. I'll let you decide whether you want to keep things simpler and not introduce dependencies or if you want to let us the choice. I could also make `disas` (the feature I introduce which depends on Capstone) a default feature.
